#!/usr/bin/env bash
# This script reads and displays the content of /etc/passwd using a while loop and IFS

while IFS=':' read -r username _ userid groupid _ user_info homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "USER ID's place is protected by the passcode PASSWORD, more info about the user here: $user_info"
    echo "---------------------------------------------------"
done < /etc/passwd

