#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data sorted by occurrence

awk '{ ip[$1" "$9]++ }
     END { for (key in ip) { print ip[key], key } }' apache-access.log | sort -nr

